// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6964.FRCBearBotsTrial2.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc6964.FRCBearBotsTrial2.subsystems.*;

/**
 *
 */
public class LeftSideAuto extends CommandGroup {
//5 inches per 0.1 seconds
	//7 inches per 0.1 second

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
	public LeftSideAuto(String m) {
		if(m.equals("")) {
			for(int a=1;a<=21;a++) {
				addSequential(new MoveForward());
			}
		} else if(m.charAt(0)=='L') {
			for(int a=1;a<=21;a++) {
				addSequential(new MoveForward());
			}
				/*for(int a=1;a<=20;a++) {
					addSequential(new MoveForward());
				}
				addSequential(new RightTurn());
				addSequential(new MoveForward());
				addSequential(new AutoArmMove());
				addSequential(new HandChange());*/	
		} else if(m.charAt(0)=='R') {
			for(int a=1;a<=20;a++) {
				addSequential(new MoveForward());
			}
			addSequential(new LeftTurn());
			addSequential(new MoveForward());
			addSequential(new AutoArmMove());
			addSequential(new HandChange());
		/*	for(int a=1;a<=21;a++) {
				addSequential(new MoveForward());
			}*/
			/*	for(int a=1;a<=34;a++) {
					addSequential(new MoveForward());
				}
				addSequential(new RightTurn());
				for(int b=1;b<=32;b++) {
					addSequential(new MoveForward());
				}
				addSequential(new RightTurn());
				for(int c=1;c<=8;c++) {
					addSequential(new MoveForward());
				}
				addSequential(new RightTurn());
				addSequential(new AutoArmMove());
				addSequential(new HandChange());*/
		}

	}
	

} 

