// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6964.FRCBearBotsTrial2.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc6964.FRCBearBotsTrial2.subsystems.*;

/**
 *
 */
public class LeftSideAuto extends CommandGroup {
	// 5 inches per 0.1 seconds
	// 7 inches per 0.1 second

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
	public LeftSideAuto(String m) {
		for (int a = 1; a <= 40; a++) {
			addSequential(new MoveForward());
		}

	}

}
