package org.usfirst.frc6964.FRCBearBotsTrial2.commands;

import org.usfirst.frc6964.FRCBearBotsTrial2.Robot;
import org.usfirst.frc6964.FRCBearBotsTrial2.RobotMap;

import edu.wpi.first.wpilibj.command.Command;

public class TestVictor extends Command {
    public TestVictor() {
//    	isClosed = false;
//    	isOpen = false;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveSubsystem);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    // Called just before this Command runs  v vthe first time
    @Override
    protected void initialize() {
    }
    
    protected void execute() {
    	if(Robot.oi.testTopLeftMotor.get()) {
    		RobotMap.driveSubsystemDifferentialDrive1.arcadeDrive(0, .5);
    	}
    }
   
  
	@Override
	protected boolean isFinished() {
		// TODO Auto-generated method stub
		return false;
	}

}
